export const BASE_URL = "/api";

export const skillsData = [
  {
    type: "Frontend Engineer",
    skills: [
      "HTML",
      "CSS",
      "JavaScript",
      "React.js",
      "Vue.js",
      "Angular",
      "TypeScript",
      "Next.js",
      "SASS/SCSS",
      "Webpack",
      "Responsive Design",
      "UI/UX Principles",
    ],
  },
  {
    type: "Backend Engineer",
    skills: [
      "Node.js",
      "Python",
      "Java",
      "C#",
      "Go",
      "Ruby on Rails",
      "Spring Boot",
      "Django",
      "Express.js",
      "SQL",
      "NoSQL",
      "Microservices Architecture",
      "API Development",
    ],
  },
  {
    type: "Full Stack Engineer",
    skills: [
      "JavaScript",
      "React",
      "Node.js",
      "MongoDB",
      "SQL",
      "GraphQL",
      "REST APIs",
      "Docker",
      "Kubernetes",
      "CI/CD",
      "Cloud Computing",
    ],
  },
  {
    type: "DevOps Engineer",
    skills: [
      "AWS",
      "Azure",
      "Google Cloud",
      "Docker",
      "Kubernetes",
      "Terraform",
      "CI/CD",
      "Jenkins",
      "Bash Scripting",
      "Linux Administration",
      "Networking",
    ],
  },
  {
    type: "Mobile Engineer",
    skills: [
      "Swift",
      "Kotlin",
      "React Native",
      "Flutter",
      "Objective-C",
      "Android SDK",
      "iOS Development",
      "Dart",
      "Xamarin",
      "Mobile UI/UX",
    ],
  },
  {
    type: "Data Engineer",
    skills: [
      "SQL",
      "Python",
      "Apache Spark",
      "Hadoop",
      "Kafka",
      "Airflow",
      "ETL Pipelines",
      "Big Data Technologies",
      "Data Warehousing",
    ],
  },
  {
    type: "Machine Learning Engineer",
    skills: [
      "Python",
      "TensorFlow",
      "PyTorch",
      "Scikit-learn",
      "Deep Learning",
      "Computer Vision",
      "NLP",
      "Data Preprocessing",
      "MLOps",
      "Model Deployment",
    ],
  },
  {
    type: "Cybersecurity Engineer",
    skills: [
      "Network Security",
      "Penetration Testing",
      "Cryptography",
      "Firewalls",
      "Security Auditing",
      "SIEM",
      "Ethical Hacking",
      "Cloud Security",
      "SOC Operations",
    ],
  },
  {
    type: "Embedded Systems Engineer",
    skills: [
      "C",
      "C++",
      "Assembly Language",
      "RTOS",
      "Microcontrollers",
      "Embedded Linux",
      "Firmware Development",
      "IoT Protocols",
      "Circuit Design",
    ],
  },
  {
    type: "Game Developer",
    skills: [
      "C++",
      "C#",
      "Unity",
      "Unreal Engine",
      "Game Physics",
      "Shader Programming",
      "3D Modeling",
      "Animation",
      "Multiplayer Networking",
    ],
  },
];
